// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpdlGAmSMn7YWuKhY3YhNQipx5pN4kiZU',
    appId: '1:550572076995:web:9ea619317bc5ea54019776',
    messagingSenderId: '550572076995',
    projectId: 'stylehub-8875e',
    authDomain: 'stylehub-8875e.firebaseapp.com',
    storageBucket: 'stylehub-8875e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYpFJVDZ7ockF5af-oH-HTOTEOFpijnXU',
    appId: '1:550572076995:android:8334344f783ae0a9019776',
    messagingSenderId: '550572076995',
    projectId: 'stylehub-8875e',
    storageBucket: 'stylehub-8875e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiSx2DPc_jWWPWPqkcT5S3bXZhvB8b2d8',
    appId: '1:550572076995:ios:e5a7ae5d5cc25807019776',
    messagingSenderId: '550572076995',
    projectId: 'stylehub-8875e',
    storageBucket: 'stylehub-8875e.firebasestorage.app',
    iosBundleId: 'com.example.stylehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiSx2DPc_jWWPWPqkcT5S3bXZhvB8b2d8',
    appId: '1:550572076995:ios:e5a7ae5d5cc25807019776',
    messagingSenderId: '550572076995',
    projectId: 'stylehub-8875e',
    storageBucket: 'stylehub-8875e.firebasestorage.app',
    iosBundleId: 'com.example.stylehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpdlGAmSMn7YWuKhY3YhNQipx5pN4kiZU',
    appId: '1:550572076995:web:cb889da4d71c93c5019776',
    messagingSenderId: '550572076995',
    projectId: 'stylehub-8875e',
    authDomain: 'stylehub-8875e.firebaseapp.com',
    storageBucket: 'stylehub-8875e.firebasestorage.app',
  );
}
